name: CD
run-name: ${{ inputs.reason }}

on:
  push:
    paths:
      - ".github/workflows/cd.yaml"
      - "**/src/**"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
  schedule:
    - cron: "0 0 1 */3 *" # Every 3 months on the first day of the month at midnight
  workflow_dispatch:
    inputs:
      reason:
        description: Dispatch reason
        required: true

env:
  PROJECT_NAME: ${{ github.event.repository.name }}
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build and Upload to Artifacts
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      attestations: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary-suffix: ""
          - os: macos-latest
            binary-suffix: ""
          - os: windows-latest
            binary-suffix: ".exe"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up or update Rust toolchain
        run: rustup toolchain install --profile default

      - name: Set-up Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}

      - name: Build project
        run: cargo build --verbose --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ runner.os }}
          path: target/release/${{ env.PROJECT_NAME }}${{ matrix.binary-suffix }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: target/release/${{ env.PROJECT_NAME }}${{ matrix.binary-suffix }}
